[package]
name = "plugin-synth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
jd-core.workspace = true
jd-dsp.workspace = true
jd-gui.workspace = true
nih_plug.workspace = true
nih_plug_egui.workspace = true
egui.workspace = true
parking_lot.workspace = true
