[package]
name = "standalone-synth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
jd-core.workspace = true
jd-dsp.workspace = true
jd-audio-io.workspace = true
jd-gui.workspace = true
eframe.workspace = true
egui.workspace = true
parking_lot.workspace = true
env_logger.workspace = true
log.workspace = true
crossbeam-channel.workspace = true
ringbuf.workspace = true
